menu:
- {name: 'CV', url: '/cv'} # In ./_data/cv and ./_layouts/cv.html
- {name: 'Projects', url: '/publications'} # In ./_data/publications.yml and ./_layouts/publications.html and ./_includes/publications.html
- {name: 'Just For Fun', url: '/courses'}
#- {name: 'cv', url: '/cv'}
# - {name: 'contact', url: '/contact'}

courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

# All social links. 
social:
- {icon: 'github', link: 'https://github.com/veronikapotter'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/'}
- {icon: 'google-scholar', link: 'https://scholar.google.com/citations?user=YOUR_USER_ID'}
- {icon: 'envelope', link: 'mailto:potter.v@northeastern.edu'}

# contacts:
# - {name: 'Dr. Academia', title: 'Professor', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/contact.jpg'}
